/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions` */
object Libs {
    /**
     * http://github.com/pholser/junit-quickcheck */
    const val junit_quickcheck_core: String = "com.pholser:junit-quickcheck-core:" +
            Versions.com_pholser

    /**
     * http://github.com/pholser/junit-quickcheck */
    const val junit_quickcheck_generators: String = "com.pholser:junit-quickcheck-generators:" +
            Versions.com_pholser

    /**
     * http://github.com/pholser/junit-quickcheck */
    const val junit_quickcheck_guava: String = "com.pholser:junit-quickcheck-guava:" +
            Versions.com_pholser

    /**
     * http://github.com/pholser/junit-quickcheck */
    const val junit_quickcheck: String = "com.pholser:junit-quickcheck:" + Versions.com_pholser

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
                    Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * http://hamcrest.org/JavaHamcrest/ */
    const val hamcrest: String = "org.hamcrest:hamcrest:" + Versions.hamcrest

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine:" +
            Versions.org_junit_jupiter

    /**
     * https://junit.org/junit5/ */
    const val junit_jupiter_params: String = "org.junit.jupiter:junit-jupiter-params:" +
            Versions.org_junit_jupiter

    /**
     * https://github.com/mockito/mockito */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

    /**
     * http://pitest.org */
    const val pitest_command_line: String = "org.pitest:pitest-command-line:" + Versions.org_pitest

    /**
     * http://pitest.org */
    const val pitest: String = "org.pitest:pitest:" + Versions.org_pitest
}
